dist: xenial
sudo: false
language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - cppcheck
            - libopencv-dev
script:
  - mkdir bin
  - cd bin/
  - cmake ..
  - scan-build cmake --build . -- -j2
