dist: trusty
sudo: false
language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cppcheck
            - libopencv-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir bin
  - cd bin/
  - cmake ..
  - scan-build cmake --build . -- -j2
