dist: xenial
sudo: false
language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-9.0
            - cppcheck
            - libopencv-dev
      env:
        - MATRIX_EVAL="CC=clang-9.0 && CXX=clang++-9.0"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir bin
  - cd bin/
  - cmake ..
  - scan-build cmake --build . -- -j2
