image:
- Visual Studio 2017
clone_folder: C:\project\archery_counter
build_script:
- cmd: >-
    choco install opencv

    dir C:\tools\opencv
    
    dir C:\tools\opencv\build

    mkdir build

    cd build
    
    cmake C:\project\archery_counter -G "Visual Studio 15" -D OpenCV_DIR=C:\tools\opencv\build
    
    cmake --build .

    cmake --build . --config Release
    

