image:
- Visual Studio 2017
clone_folder: C:\project\archery_counter
build_script:
- cmd: >-
    choco install opencv --params="'/Environment'"
    
    refreshenv
    
    dir C:\tools\opencv
    
    dir C:\tools\opencv\sources
    
    dir C:\tools\opencv\build
    
    dir C:\tools\opencv\build\bin
    
    dir C:\tools\opencv\build\x64\vc15
    
    dir C:\tools\opencv\build\x64\vc15\bin

    dir C:\tools\opencv\build\x64\vc15\lib


    mkdir build

    cd build
    
    cmake C:\project\archery_counter -G "Visual Studio 15"
    
    cmake --build .

    cmake --build . --config Release
    

